extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern u8 bob_dl_Pic__37__i8[];
extern Vtx bob_dl_Cube_mesh_vtx_0[24];
extern Gfx bob_dl_Cube_mesh_tri_0[];
extern Gfx mat_bob_dl_sm64_material[];
extern Gfx bob_dl_Cube_mesh[];
extern Gfx bob_dl_material_revert_render_settings[];
